### PR TITLE
Write contributors into outputFiles rather than package.json

### PR DESCRIPTION
**Pull request by outsideris**
As @juergba [said](https://github.com/mochajs/mocha/pull/4041#pullrequestreview-296882461), putting all contributors on `package.json` doesn't make sense.

So, add an `outputFile` option to save all contributors on another file(e.g `CONTRIBUTORS`) than `package.json`.

### CODE REVIEW

**Comment by juergba** [comment]
@outsideris this package is boneskull's baby, so IMO it's upto him to review.
Anyway the docu update in "README.md" is missing.

**Comment by boneskull** [comment]
it was always in package.json, which is why I wrote the tool to put it there. there are other tools to generate a list of contributors and output to markdown... 

but contributors.md is supposed to be a contribution guide, not a list of contributors. 

so if we’re going to abandon writing to package.json (not sure why this is a problem, but haven’t investigated where this issue can from), then we should:

1. use maybe AUTHORS.md to put the names
2. don’t change this package, because it’s meant to write to package.json, and other tools do number 1
3. use some other tool
4. ensure the .md file is written to at publish time
5. archive this package

**Comment by boneskull** [comment]
and yes, to be more clear, there’s no reason for this package other than “we’ve always done it that way” which is a thin reason indeed

**Comment by outsideris** [comment]
Sorry, I should discuss about that in advance. I didn't think it will be a problem to add a feature to this package.

I opened [a issue](https://github.com/mochajs/mocha/issues/4053) to discuss them.

**Comment by boneskull** [comment]
@outsideris don't worry!  it's just that the problem of listing contributors in a markdown file has already been solved elsewhere.  if that's the direction we're to go in, we shouldn't need to maintain our own software to do it.

**Pull request closed without merging**
